// <auto-generated />
using System;
using Course4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
#nullable disable
namespace Course4.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            modelBuilder.Entity("Course4.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Authors_Name");
                    b.ToTable("Authors");
                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Лев Толстой"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1821, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Фёдор Достоевский"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1860, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Антон Чехов"
                        });
                });
            modelBuilder.Entity("Course4.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");
                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
                    b.HasKey("Id");
                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Books_AuthorId");
                    b.HasIndex("PublishedYear")
                        .HasDatabaseName("IX_Books_PublishedYear");
                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Books_Title");
                    b.ToTable("Books");
                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = 1869,
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublishedYear = 1877,
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            PublishedYear = 1866,
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            PublishedYear = 1904,
                            Title = "Вишнёвый сад"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            PublishedYear = 1880,
                            Title = "Братья Карамазовы"
                        });
                });
            modelBuilder.Entity("Course4.Models.Book", b =>
                {
                    b.HasOne("Course4.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Author");
                });
            modelBuilder.Entity("Course4.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
